# Generated by Django 4.0 on 2021-12-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query_archived',
            name='hash_value',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query_archived',
            name='query_string',
            field=models.TextField(max_length=1000),
        ),
    ]
