# Generated by Django 4.0 on 2021-12-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_query_archived_hash_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query_archived',
            name='hash_value',
        ),
    ]
