# Generated by Django 4.0 on 2021-12-14 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query_archived',
            name='hash_value',
        ),
        migrations.AlterField(
            model_name='query_archived',
            name='date_created_at',
            field=models.DateField(default=datetime.date(2021, 12, 14)),
        ),
    ]
