# Generated by Django 4.0 on 2021-12-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_tweets', '0002_remove_query_archived_hash_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query_Archived',
        ),
    ]
